export default {
  CLEAR_DATA_AUTH: 'CLEAR_DATA_AUTH',

  UPDATE_USER_INFO: 'UPDATE_USER_INFO',

  SET_STATE_SPLASH: 'SET_STATE_SPLASH',

  UPDATE_LIST_PLAN: 'UPDATE_LIST_PLAN',

  CLEAR_LIST_PLAN: 'CLEAR_LIST_PLAN',
};
